name: "Test chromedriver on *NIX"
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    branches:
      - '*'
    paths:
      - '**'
      - '!*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        branch: [ 'master', 'now' ]
    steps:
    - uses: actions/checkout@v3
    - if: matrix.os == 'ubuntu-latest'
      run: echo 'CHROMEAPP=google-chrome' >> $GITHUB_ENV
    - if: matrix.os == 'macos-latest'
      run: echo 'CHROMEAPP=/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' >> $GITHUB_ENV
    - run: rm -rf node_modules && yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
    - run: |
        CHROME_VERSION=$("$CHROMEAPP" --version | cut -f 3 -d ' ' | cut -d '.' -f 1)
        echo "CHROMEDRIVER_VERSION=$(curl --location --fail --retry 10 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})" >> $GITHUB_ENV
    - uses: ./
      if: matrix.branch == 'now'
      with:
        chromedriver-version: ${{ env.CHROMEDRIVER_VERSION }}
    - uses: nanasess/setup-chromedriver@master
      if: matrix.branch == 'master'
      with:
        chromedriver-version: ${{ env.CHROMEDRIVER_VERSION }}
    - name: setup
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # disable headless mode
        yarn ts-node $GITHUB_WORKSPACE/__tests__/chromedriver.ts

  test_default_version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        branch: [ 'master', 'now' ]
    steps:
    - uses: actions/checkout@v3
    - if: matrix.os == 'ubuntu-latest'
      run: echo 'CHROMEAPP=google-chrome' >> $GITHUB_ENV
    - if: matrix.os == 'macos-latest'
      run: echo 'CHROMEAPP=/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' >> $GITHUB_ENV
    - run: rm -rf node_modules && yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
    - uses: ./
      if: matrix.branch == 'now'
    - uses: nanasess/setup-chromedriver@master
      if: matrix.branch == 'master'
    - name: setup
      run: |
        "$CHROMEAPP" --version
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # disable headless mode
        yarn ts-node $GITHUB_WORKSPACE/__tests__/chromedriver.ts
