name: "Test chromedriver on Windows"
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    branches:
      - '*'
    paths:
      - '**'
      - '!*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, windows-2019 ]
        branch: [ 'master', 'now' ]
    steps:
    - uses: actions/checkout@v3
    - shell: pwsh
      run: echo "CHROMEAPP=C:\Program Files\Google\Chrome\Application\chrome.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    - run: rm -rf node_modules && yarn install --frozen-lockfile
      shell: bash
    - run: yarn build
    - run: yarn test
    - shell: pwsh
      run: |
        $chrome_fullversion = (Get-Item $Env:CHROMEAPP).VersionInfo.FileVersion
        $chrome_majorversion = $chrome_fullversion.Split(".")[0]
        $response = Invoke-WebRequest "http://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chrome_majorversion"
        $version = $response.Content
        echo "CHROMEDRIVER_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    - uses: ./
      if: matrix.branch == 'now'
      with:
        chromedriver-version: ${{ env.CHROMEDRIVER_VERSION }}
    - uses: nanasess/setup-chromedriver@master
      if: matrix.branch == 'master'
      with:
        chromedriver-version: ${{ env.CHROMEDRIVER_VERSION }}
    - name: setup
      run: |
        chromedriver --url-base=/wd/hub &
        yarn ts-node "$Env:GITHUB_WORKSPACE\__tests__\chromedriver.ts"

  test_default_version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, windows-2019 ]
        branch: [ 'master', 'now' ]
    steps:
    - uses: actions/checkout@v3
    - shell: pwsh
      run: echo "CHROMEAPP=C:\Program Files\Google\Chrome\Application\chrome.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    - run: rm -rf node_modules && yarn install --frozen-lockfile
      shell: bash
    - run: yarn build
    - run: yarn test
    - uses: ./
      if: matrix.branch == 'now'
    - uses: nanasess/setup-chromedriver@master
      if: matrix.branch == 'master'
    - name: setup
      run: |
        chromedriver --url-base=/wd/hub &
        yarn ts-node "$Env:GITHUB_WORKSPACE\__tests__\chromedriver.ts"
